stages:
  - build

build:
  stage: build
  image: registry.gitlab.com/schoentoon/grafana-plugin-ci:latest
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn build --coverage
    - mage -v buildAll
    - mage -v lint
    - mage -v coverage
  artifacts:
    paths:
      - dist
