stages:
  - build
  - pages

build:
  stage: build
  image: registry.gitlab.com/schoentoon/grafana-plugin-ci:latest
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn build --coverage
    - mage -v buildAll
    - mage -v lint
    - mage -v coverage
  after_script:
    - mv dist schoentoon-exchangerates-datasource
    - zip schoentoon-exchangerates-datasource-0.1.zip schoentoon-exchangerates-datasource -r
  artifacts:
    paths:
      - ./*.zip

pages:
  stage: pages
  image: alpine:latest
  only:
    - master
  dependencies:
    - build
  script:
    - mkdir public
    - mv *.zip public/
  artifacts:
    paths:
      - public
